name: Continuous Integration

on:
  - pull_request

jobs:
  zeitdl-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run pre-commit
        run: uvx pre-commit run --all-files
