name: Continuous Integration

on:
  - pull_request

jobs:
  zeitdl-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install pipx
        run: pip install --upgrade pipx

      - name: Run pre-commit
        run: pipx run pre-commit run --all-files
